# Generated by Django 5.1.1 on 2025-02-10 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ObservedProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('notation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('notation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WaterBodyCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('notation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WaterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('monitoring_site_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('monitoring_site_identifier_scheme', models.CharField(blank=True, choices=[('eionetMonitoringSiteCode', 'EIONET identifier'), ('euMonitoringSiteCode', 'WFD identifier')], max_length=50, null=True)),
                ('phenomenon_time_reference_year', models.IntegerField(blank=True, null=True)),
                ('parameter_sampling_period', models.CharField(blank=True, max_length=100, null=True)),
                ('procedure_loq_value', models.FloatField(blank=True, null=True)),
                ('result_number_of_samples', models.IntegerField(blank=True, null=True)),
                ('result_quality_number_of_samples_below_loq', models.IntegerField(blank=True, null=True)),
                ('result_quality_minimum_below_loq', models.BooleanField(blank=True, null=True)),
                ('result_minimum_value', models.FloatField(blank=True, null=True)),
                ('result_quality_mean_below_loq', models.BooleanField(blank=True, null=True)),
                ('result_mean_value', models.FloatField(blank=True, null=True)),
                ('result_quality_maximum_below_loq', models.BooleanField(blank=True, null=True)),
                ('result_maximum_value', models.FloatField(blank=True, null=True)),
                ('result_quality_median_below_loq', models.BooleanField(blank=True, null=True)),
                ('result_median_value', models.FloatField(blank=True, null=True)),
                ('result_standard_deviation_value', models.FloatField(blank=True, null=True)),
                ('procedure_analytical_method', models.CharField(blank=True, max_length=255, null=True)),
                ('parameter_sample_depth', models.FloatField(blank=True, null=True)),
                ('result_observation_status', models.CharField(blank=True, choices=[('A', 'Record is confirmed as correct'), ('L', 'Missing observed value, the data were not collected'), ('M', 'Missing observed value, the data can not exist'), ('N', 'Missing observed value, observed value is not relevant or not significant'), ('O', 'Missing observed value, no further information is available'), ('W', 'Missing observed value, data are included in another source category'), ('X', 'Reported value includes data from another source category'), ('Y', 'The source category does not exactly match the standard definition'), ('Z', 'Record reported in the past should be deleted')], max_length=1, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startapp.country')),
                ('observed_property_determinand_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startapp.observedproperty')),
                ('parameter_water_body_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startapp.waterbodycategory')),
                ('procedure_analysed_matrix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startapp.matrix')),
                ('result_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startapp.unitofmeasure')),
            ],
        ),
    ]
