# Generated by Django 5.1.6 on 2025-03-07 18:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleanedData',
            fields=[
                ('countryCode', models.CharField(max_length=255)),
                ('monitoringSiteIdentifier', models.CharField(blank=True, max_length=255, null=True)),
                ('monitoringSiteIdentifierScheme', models.CharField(blank=True, max_length=255, null=True)),
                ('parameterWaterBodyCategory', models.CharField(blank=True, max_length=255, null=True)),
                ('observedPropertyDeterminandCode', models.CharField(blank=True, max_length=255, null=True)),
                ('observedPropertyDeterminandLabel', models.CharField(blank=True, max_length=255, null=True)),
                ('procedureAnalysedMatrix', models.CharField(blank=True, max_length=255, null=True)),
                ('resultUom', models.CharField(blank=True, max_length=255, null=True)),
                ('phenomenonTimeReferenceYear', models.IntegerField(blank=True, null=True)),
                ('parameterSamplingPeriod', models.CharField(blank=True, max_length=100, null=True)),
                ('procedureLOQValue', models.FloatField(blank=True, null=True)),
                ('resultNumberOfSamples', models.FloatField(blank=True, null=True)),
                ('resultQualityNumberOfSamplesBelowLOQ', models.IntegerField(blank=True, null=True)),
                ('resultQualityMinimumBelowLOQ', models.IntegerField(blank=True, null=True)),
                ('resultMinimumValue', models.FloatField(blank=True, null=True)),
                ('resultQualityMeanBelowLOQ', models.IntegerField(blank=True, null=True)),
                ('resultMeanValue', models.FloatField(blank=True, null=True)),
                ('resultQualityMaximumBelowLOQ', models.IntegerField(blank=True, null=True)),
                ('resultMaximumValue', models.FloatField(blank=True, null=True)),
                ('resultQualityMedianBelowLOQ', models.IntegerField(blank=True, null=True)),
                ('resultMedianValue', models.FloatField(blank=True, null=True)),
                ('resultStandardDeviationValue', models.FloatField(blank=True, null=True)),
                ('procedureAnalyticalMethod', models.CharField(blank=True, max_length=255, null=True)),
                ('parameterSampleDepth', models.FloatField(blank=True, null=True)),
                ('resultObservationStatus', models.CharField(blank=True, max_length=1, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('UID', models.CharField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'cleaned_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('isoalpha2', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CountryStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.TextField(blank=True, null=True)),
                ('iso_alpha2', models.CharField(blank=True, max_length=3, null=True)),
                ('total_monitoring_sites', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('decades_covered', models.TextField(blank=True, null=True)),
                ('water_body_category', models.TextField(blank=True, null=True)),
                ('matrix', models.TextField(blank=True, null=True)),
                ('count_of_chemicals_monitored', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('number_of_collected_samples', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('proportion_of_confirmed_samples', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('most_monitored_determinand', models.TextField(blank=True, null=True)),
                ('total_samples', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('mean_concentration', models.TextField(blank=True, null=True)),
                ('standard_deviation', models.TextField(blank=True, null=True)),
                ('minimum_recorded_value', models.TextField(blank=True, null=True)),
                ('maximum_recorded_value', models.TextField(blank=True, null=True)),
                ('unit_of_measure', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'country_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('observed_property_determinand', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_year', models.IntegerField(blank=True, null=True)),
                ('matrix', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_collected_samples', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('nominator_of_confirmed_samples', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('denominator_of_confirmed_samples', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('result_mean_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('stddev', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('result_minimum_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('result_maximum_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('uom', models.TextField(blank=True, null=True)),
                ('under_loq', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('above_loq', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('list_of_water_body_category', models.TextField(blank=True, null=True)),
                ('list_of_monitoring_sites', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dashboard_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('iso_alpha2', models.CharField(blank=True, max_length=3, null=True)),
                ('observed_property_determinand', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_year', models.IntegerField(blank=True, null=True)),
                ('matrix', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'filters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(help_text='Celery task ID', max_length=255, unique=True)),
                ('model_name', models.CharField(default='Unknown', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('results', models.JSONField(default='', help_text='Stores the results of the pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='WaterData',
            fields=[
                ('countryCode', models.CharField(max_length=255)),
                ('monitoringSiteIdentifier', models.CharField(blank=True, max_length=255, null=True)),
                ('monitoringSiteIdentifierScheme', models.CharField(blank=True, max_length=255, null=True)),
                ('parameterWaterBodyCategory', models.CharField(blank=True, max_length=255, null=True)),
                ('observedPropertyDeterminandCode', models.CharField(blank=True, max_length=255, null=True)),
                ('observedPropertyDeterminandLabel', models.CharField(blank=True, max_length=255, null=True)),
                ('procedureAnalysedMatrix', models.CharField(blank=True, max_length=255, null=True)),
                ('resultUom', models.CharField(blank=True, max_length=255, null=True)),
                ('phenomenonTimeReferenceYear', models.IntegerField(blank=True, null=True)),
                ('parameterSamplingPeriod', models.CharField(blank=True, max_length=100, null=True)),
                ('procedureLOQValue', models.FloatField(blank=True, null=True)),
                ('resultNumberOfSamples', models.FloatField(blank=True, null=True)),
                ('resultQualityNumberOfSamplesBelowLOQ', models.IntegerField(blank=True, null=True)),
                ('resultQualityMinimumBelowLOQ', models.IntegerField(blank=True, null=True)),
                ('resultMinimumValue', models.FloatField(blank=True, null=True)),
                ('resultQualityMeanBelowLOQ', models.IntegerField(blank=True, null=True)),
                ('resultMeanValue', models.FloatField(blank=True, null=True)),
                ('resultQualityMaximumBelowLOQ', models.IntegerField(blank=True, null=True)),
                ('resultMaximumValue', models.FloatField(blank=True, null=True)),
                ('resultQualityMedianBelowLOQ', models.IntegerField(blank=True, null=True)),
                ('resultMedianValue', models.FloatField(blank=True, null=True)),
                ('resultStandardDeviationValue', models.FloatField(blank=True, null=True)),
                ('procedureAnalyticalMethod', models.CharField(blank=True, max_length=255, null=True)),
                ('parameterSampleDepth', models.FloatField(blank=True, null=True)),
                ('resultObservationStatus', models.CharField(blank=True, max_length=1, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('UID', models.CharField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
