# Generated by Django 5.1.6 on 2025-03-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.TextField(blank=True, null=True)),
                ('isoalpha2', models.CharField(max_length=2)),
                ('phenomenon_time_reference_year', models.IntegerField(blank=True, null=True)),
                ('observed_property_determinand', models.TextField(blank=True, null=True)),
                ('total_monitoring_sites', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('water_body_category', models.TextField(blank=True, null=True)),
                ('matrix', models.TextField(blank=True, null=True)),
                ('proportion_of_confirmed_samples', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('loq_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('number_of_collected_samples', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('number_samples_below_loq', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('mean_concentration', models.TextField(blank=True, null=True)),
                ('number_samples_mean_below_loq', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('median_concentration', models.TextField(blank=True, null=True)),
                ('number_samples_median_below_loq', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('standard_deviation', models.TextField(blank=True, null=True)),
                ('minimum_recorded_value', models.TextField(blank=True, null=True)),
                ('number_samples_min_below_loq', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('maximum_recorded_value', models.TextField(blank=True, null=True)),
                ('number_samples_max_below_loq', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('unit_of_measure', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chat_data',
                'managed': False,
            },
        ),
    ]
