# Generated by Django 5.1.1 on 2024-09-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='lang',
            field=models.TextField(default='en'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='phone',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
